//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaMdEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaMdEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 You already have the latest version of this application. 的本地化字符串。
        /// </summary>
        internal static string AlreadyLatestVersion {
            get {
                return ResourceManager.GetString("AlreadyLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find to &amp;Next 的本地化字符串。
        /// </summary>
        internal static string ButtonFindNext {
            get {
                return ResourceManager.GetString("ButtonFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find to &amp;Previous 的本地化字符串。
        /// </summary>
        internal static string ButtonFindPrev {
            get {
                return ResourceManager.GetString("ButtonFindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace to &amp;Next 的本地化字符串。
        /// </summary>
        internal static string ButtonReplaceNext {
            get {
                return ResourceManager.GetString("ButtonReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace to &amp;Previous 的本地化字符串。
        /// </summary>
        internal static string ButtonReplacePrev {
            get {
                return ResourceManager.GetString("ButtonReplacePrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string DialogTitleInfo {
            get {
                return ResourceManager.GetString("DialogTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string DialogTitleNotice {
            get {
                return ResourceManager.GetString("DialogTitleNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        internal static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get the latest version information. 的本地化字符串。
        /// </summary>
        internal static string ErrorGetNewVersion {
            get {
                return ResourceManager.GetString("ErrorGetNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Changed) 的本地化字符串。
        /// </summary>
        internal static string FlagChanged {
            get {
                return ResourceManager.GetString("FlagChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one were read.\nDo you wish to convert all files to HTML files on this options?
        ///if you select &apos;No&apos;, all files will be opend without converting. 的本地化字符串。
        /// </summary>
        internal static string MsgConvertAllFilesToHTML {
            get {
                return ResourceManager.GetString("MsgConvertAllFilesToHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Default) 的本地化字符串。
        /// </summary>
        internal static string MsgDefaultCSS {
            get {
                return ResourceManager.GetString("MsgDefaultCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during deleting temporary file!\na temporary file may be left in the folder the file is edited.
        ///This file is not a problem even if you delete it manually. 的本地化字符串。
        /// </summary>
        internal static string MsgErrorDeleteTemporaryFile {
            get {
                return ResourceManager.GetString("MsgErrorDeleteTemporaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching completed to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? 的本地化字符串。
        /// </summary>
        internal static string MsgFindCompleteToBegining {
            get {
                return ResourceManager.GetString("MsgFindCompleteToBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching completed to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? 的本地化字符串。
        /// </summary>
        internal static string MsgFindCompleteToBeginning {
            get {
                return ResourceManager.GetString("MsgFindCompleteToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching completed to the end of this file.
        ///Do you wish to continue searching from the beginning of this file? 的本地化字符串。
        /// </summary>
        internal static string MsgFindCompleteToEnd {
            get {
                return ResourceManager.GetString("MsgFindCompleteToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you remove this file in list, and move to trash? 的本地化字符串。
        /// </summary>
        internal static string MsgMoveToTrash {
            get {
                return ResourceManager.GetString("MsgMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find Help file. Opening this file has failed. 的本地化字符串。
        /// </summary>
        internal static string MsgNoHelpFile {
            get {
                return ResourceManager.GetString("MsgNoHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find sample MD file.\nOpening this file has failed. 的本地化字符串。
        /// </summary>
        internal static string MsgNoSampleFile {
            get {
                return ResourceManager.GetString("MsgNoSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The word was not found. 的本地化字符串。
        /// </summary>
        internal static string MsgNotFound {
            get {
                return ResourceManager.GetString("MsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Association tool is not found, therefore failed to associate .md files with this application. 的本地化字符串。
        /// </summary>
        internal static string MsgNotFoundAssociationTool {
            get {
                return ResourceManager.GetString("MsgNotFoundAssociationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The word could not find to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? 的本地化字符串。
        /// </summary>
        internal static string MsgNotFoundToBegining {
            get {
                return ResourceManager.GetString("MsgNotFoundToBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The word could not find to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? 的本地化字符串。
        /// </summary>
        internal static string MsgNotFoundToBeginning {
            get {
                return ResourceManager.GetString("MsgNotFoundToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The word could not find the word to the end of this file.
        ///Do you wish to continue searching from the beginning of this file? 的本地化字符串。
        /// </summary>
        internal static string MsgNotFoundToEnd {
            get {
                return ResourceManager.GetString("MsgNotFoundToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file has been output to the clipboard. 的本地化字符串。
        /// </summary>
        internal static string MsgOutputToClipboard {
            get {
                return ResourceManager.GetString("MsgOutputToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  of the word were replaced. 的本地化字符串。
        /// </summary>
        internal static string MsgReplaced {
            get {
                return ResourceManager.GetString("MsgReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To change the setting of language, it is necessary to restart the application.
        ///Do you want to restart this application now? 的本地化字符串。
        /// </summary>
        internal static string MsgRestartApplication {
            get {
                return ResourceManager.GetString("MsgRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same CSS file exitsts already. 的本地化字符串。
        /// </summary>
        internal static string MsgSameCSSFileExists {
            get {
                return ResourceManager.GetString("MsgSameCSSFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same file exists.\nContinue to overwrite? 的本地化字符串。
        /// </summary>
        internal static string MsgSameFileOverwrite {
            get {
                return ResourceManager.GetString("MsgSameFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file being edited. Do you wish to save before exiting? 的本地化字符串。
        /// </summary>
        internal static string MsgSaveFileToEnd {
            get {
                return ResourceManager.GetString("MsgSaveFileToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file being edited. Do you wish to save before starting new file? 的本地化字符串。
        /// </summary>
        internal static string MsgSaveFileToNewFile {
            get {
                return ResourceManager.GetString("MsgSaveFileToNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file being edited. Do you wish to save before opening file? 的本地化字符串。
        /// </summary>
        internal static string MsgSaveFileToOpenFile {
            get {
                return ResourceManager.GetString("MsgSaveFileToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Enter Text 的本地化字符串。
        /// </summary>
        internal static string MsgSearchInputBoxTip {
            get {
                return ResourceManager.GetString("MsgSearchInputBoxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string MsgSearchInputBoxTitle {
            get {
                return ResourceManager.GetString("MsgSearchInputBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These CSS files is found. Do you add these files to list? 的本地化字符串。
        /// </summary>
        internal static string MsgTheseCSSFilesFound {
            get {
                return ResourceManager.GetString("MsgTheseCSSFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version was found! Do you open the download site? 的本地化字符串。
        /// </summary>
        internal static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (No title) 的本地化字符串。
        /// </summary>
        internal static string NoFileName {
            get {
                return ResourceManager.GetString("NoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No CSS file 的本地化字符串。
        /// </summary>
        internal static string toolTipCssFileName {
            get {
                return ResourceManager.GetString("toolTipCssFileName", resourceCulture);
            }
        }
    }
}
